# Generated by Django 5.1.6 on 2025-02-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock50MA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('start_swing', models.CharField(max_length=5)),
                ('start_price', models.FloatField()),
                ('end_date', models.DateField()),
                ('end_swing', models.CharField(max_length=5)),
                ('end_price', models.FloatField()),
                ('entry', models.FloatField()),
                ('sl', models.FloatField()),
                ('window', models.IntegerField()),
                ('period', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=10)),
                ('market', models.CharField(max_length=10)),
                ('moving_average_50', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(max_length=1000)),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
