# Generated by Django 5.1.6 on 2025-02-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('trade', models.CharField(max_length=10)),
                ('market', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('notes', models.CharField(max_length=1000)),
                ('raw_data', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
