# Generated by Django 5.1.6 on 2025-02-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('close_price', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stock_symbol', 'date')},
            },
        ),
    ]
