# Generated by Django 5.1.6 on 2025-02-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_stockpricedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock50MA',
            new_name='Stockhalfbat',
        ),
        migrations.CreateModel(
            name='Stocks50MA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('moving_average_50', models.FloatField()),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stock_symbol', 'date')},
            },
        ),
    ]
