# Generated by Django 5.1.6 on 2025-02-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_stock50ma_stockhalfbat_stocks50ma'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks50ma',
            name='moving_average_20',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
