# Generated by Django 5.1.6 on 2025-03-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_stocks50ma_moving_average_20'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks50ma',
            name='cmp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='status',
            field=models.IntegerField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='stock_cmp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
