# Generated by Django 5.1.6 on 2025-03-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_stocks50ma_cmp_date_stocks50ma_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks50ma',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
