# Generated by Django 5.1.6 on 2025-04-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_stocks50ma_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockpricedata',
            old_name='stock_symbol',
            new_name='stock_code',
        ),
        migrations.RenameField(
            model_name='stocks50ma',
            old_name='stock_symbol',
            new_name='stock_code',
        ),
        migrations.AlterUniqueTogether(
            name='stockpricedata',
            unique_together={('stock_code', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='stocks50ma',
            unique_together={('stock_code', 'date')},
        ),
        migrations.AddField(
            model_name='stockhalfbat',
            name='stock_code',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='script',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='script',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhalfbat',
            name='script',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
