# Generated by Django 5.1.6 on 2025-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_stock_symbol_stockpricedata_stock_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='market',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='raw_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='script',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='trade',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
