# Generated by Django 5.1.6 on 2025-04-10 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_import_percent_alter_import_market_alter_import_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Import',
            new_name='Source',
        ),
    ]
