# Generated by Django 5.1.6 on 2025-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_rename_import_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks50ma',
            name='percent_50sma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='range_50ma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='target_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='target_2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
