# Generated by Django 5.1.6 on 2025-04-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_stocks50ma_percent_50sma_stocks50ma_range_50ma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks50ma',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
