# Generated by Django 5.1.6 on 2025-05-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_stocks50ma_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks50ma',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
