# Generated by Django 5.1.6 on 2025-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_stocks50ma_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks50ma',
            name='pre_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
