# Generated by Django 5.1.6 on 2025-07-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_stocks50ma_pre_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks50ma',
            name='live50ma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='live9ma',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
