# Generated by Django 5.1.6 on 2025-07-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_stocks50ma_live50ma_stocks50ma_live9ma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks50ma',
            name='live50ma',
        ),
        migrations.RemoveField(
            model_name='stocks50ma',
            name='live9ma',
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='live21ma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='live50ma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='live9ma',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
