# Generated by Django 5.1.6 on 2025-07-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_remove_stocks50ma_live50ma_remove_stocks50ma_live9ma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricedata',
            name='cp50ma',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
