# Generated by Django 5.1.6 on 2025-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_stockpricedata_cp50ma'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricedata',
            name='live921',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
