# Generated by Django 5.1.6 on 2025-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_stockpricedata_live921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricedata',
            name='live921',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
