# Generated by Django 5.1.6 on 2025-08-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_alter_stockpricedata_live921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks50ma',
            old_name='percent_50sma',
            new_name='percent_09ma',
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='percent_20ma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='percent_50ma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='range_09ma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='range_20ma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocks50ma',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
