# Generated by Django 5.1.6 on 2025-08-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_rename_percent_50sma_stocks50ma_percent_09ma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks50ma',
            name='moving_average_09',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
