# Generated by Django 5.1.6 on 2025-08-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_stocks50ma_moving_average_09'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricedata',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
