# Generated by Django 5.1.6 on 2026-08-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_stockpricedata_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockpricedata',
            old_name='script',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='stocks50ma',
            old_name='script',
            new_name='ticker',
        ),
    ]
