# Generated by Django 5.1.6 on 2026-08-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name': 'App setting', 'verbose_name_plural': 'App settings'},
        ),
    ]
