"""
Django settings for idirect (VPS / production package).
Generated by 'django-admin startproject' using Django 5.1.6.
Loads environment variables from: idirect/.env
"""
import os
from pathlib import Path
from decouple import config, Csv

from celery.schedules import crontab
from decouple import Config, Csv, RepositoryEnv

BASE_DIR = Path(__file__).resolve().parent.parent

# Always load env from the idirect folder (VPS convention)
ENV_FILE = Path(__file__).resolve().parent / ".env"
if not ENV_FILE.exists():
    raise FileNotFoundError(
        f"Missing env file: {ENV_FILE}. "
        "Copy idirect/.env.example to idirect/.env and fill values."
    )
config = Config(RepositoryEnv(str(ENV_FILE)))
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="https://idjango.rbynex.in",
    cast=Csv(),
)

INSTALLED_APPS = [
    "django_htmx",
    "coredata.apps.CoredataConfig",
    "data",
    "stocks",
    "infra",
    "django.contrib.humanize",
    "django_celery_beat",
    "django_extensions",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "idirect.urls"
WSGI_APPLICATION = "idirect.wsgi.application"
ASGI_APPLICATION = "idirect.asgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates", BASE_DIR / "static"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "coredata.context_processors.coredata_context",
            ],
        },
    },
]

# Database — TCP for Docker; optional unix socket for local MySQL
_db = {
    "ENGINE": "django.db.backends.mysql",
    "NAME": config("DATABASE_NAME"),
    "USER": config("DATABASE_USER"),
    "PASSWORD": config("DATABASE_PASSWORD"),
    "HOST": config("DATABASE_HOST", default="localhost"),
    "PORT": config("DATABASE_PORT", default="3306"),
}
if config("DATABASE_USE_SOCKET", default=False, cast=bool):
    _db["OPTIONS"] = {
        "unix_socket": config(
            "DATABASE_SOCKET", default="/var/run/mysqld/mysqld.sock"
        ),
    }
DATABASES = {"default": _db}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# Beat crontabs (9–15, 16:30) are Indian market hours, not UTC.
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "desk_review"
LOGOUT_REDIRECT_URL = "login"

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "media/"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

BREEZE_API_KEY = config("BREEZE_API_KEY", default="")
BREEZE_SECRET_KEY = config("BREEZE_SECRET_KEY", default="")
BREEZE_SESSION = config("BREEZE_SESSION", default="")
# Strip: .env typos like "GSHEET_ID = ..." or quoted values break lookups.
GSHEET_KEY = str(config("GSHEET_KEY", default="") or "").strip().strip('"').strip("'")
GSHEET_ID = str(config("GSHEET_ID", default="") or "").strip().strip('"').strip("'")
GSHEET_APP_SCRIPT = str(config("GSHEET_APP_SCRIPT", default="") or "").strip()
GSHEET_APP_SCRIPT_CMP = str(config("GSHEET_APP_SCRIPT_CMP", default="") or "").strip()
SMA_API_KEY = config("SMA_API_KEY", default="")

REDIS_HOST = config("REDIS_HOST", default="localhost")
REDIS_PORT = config("REDIS_PORT", default=6379, cast=int)
CELERY_BROKER_URL = config(
    "CELERY_BROKER_URL", default=f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND", default=f"redis://{REDIS_HOST}:{REDIS_PORT}/1"
)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [(REDIS_HOST, REDIS_PORT)]},
    },
}

PAPER_TRADING_MODE = config("PAPER_TRADING_MODE", default=True, cast=bool)
TRADING_ENABLED = config("TRADING_ENABLED", default=False, cast=bool)
MAX_POSITION_SIZE = config("MAX_POSITION_SIZE", default=100000, cast=int)
MAX_PORTFOLIO_EXPOSURE = config("MAX_PORTFOLIO_EXPOSURE", default=50.0, cast=float)
MAX_DAILY_LOSS = config("MAX_DAILY_LOSS", default=5000, cast=int)
MAX_DRAWDOWN = config("MAX_DRAWDOWN", default=10.0, cast=float)
STRATEGY_UPDATE_INTERVAL = config("STRATEGY_UPDATE_INTERVAL", default=60, cast=int)
SIGNAL_VALIDATION_WINDOW = config("SIGNAL_VALIDATION_WINDOW", default=5, cast=int)
ORDER_MAX_RETRIES = config("ORDER_MAX_RETRIES", default=3, cast=int)
ORDER_RETRY_DELAY = config("ORDER_RETRY_DELAY", default=1.0, cast=float)
MONITORING_ENABLED = config("MONITORING_ENABLED", default=True, cast=bool)
ALERT_EMAIL_ENABLED = config("ALERT_EMAIL_ENABLED", default=True, cast=bool)

CELERY_BEAT_SCHEDULE = {
    # Path A ingest — ChartInk universe after close, then CMP + ICICI tickers
    "ingest-50ma-eod": {
        "task": "data.tasks.ingest_50ma_eod",
        "schedule": crontab(minute=30, hour=16),
    },
    # Path A live CMPs so status 8 can appear during market hours
    "ingest-price-data": {
        "task": "data.tasks.ingest_price_data",
        "schedule": crontab(minute="*/5", hour="9-15"),
    },
    "execute-50ma-orders": {
        "task": "data.tasks.execute_50ma_orders",
        "schedule": crontab(minute="*/1", hour="9-15"),
    },
    "monitor-50ma-positions": {
        "task": "data.tasks.monitor_50ma_positions",
        "schedule": crontab(minute="*/1", hour="9-15"),
    },
    "update-50ma-statuses": {
        "task": "data.tasks.update_50ma_statuses",
        "schedule": crontab(minute="*/5", hour="9-15"),
    },
    # Path B framework only — 50MA_Strategy is skipped inside these tasks
    "process-strategy-signals": {
        "task": "stocks.tasks.process_strategy_signals",
        "schedule": crontab(minute="*/1", hour="9-15"),
    },
    "execute-pending-signals": {
        "task": "stocks.tasks.execute_pending_signals",
        "schedule": crontab(minute="*/1", hour="9-15"),
    },
    "monitor-positions": {
        "task": "stocks.tasks.monitor_positions",
        "schedule": crontab(minute="*/1", hour="9-15"),
    },
    "update-trailing-stops": {
        "task": "stocks.tasks.update_trailing_stops",
        "schedule": crontab(minute="*/5", hour="9-15"),
    },
    "reconcile-positions": {
        "task": "stocks.tasks.reconcile_positions",
        "schedule": crontab(minute="*/5", hour="9-15"),
    },
    "check-risk-limits": {
        "task": "stocks.tasks.check_risk_limits",
        "schedule": crontab(minute="*/5", hour="9-15"),
    },
    "calculate-performance-metrics": {
        "task": "stocks.tasks.calculate_performance_metrics",
        "schedule": crontab(minute=30, hour=15),
    },
}

TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN", default="")
TELEGRAM_CHAT_ID = config("TELEGRAM_CHAT_ID", default="")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Console logging → visible via: docker logs -f idjango
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
