# Generated by Django 5.1.6 on 2025-07-27 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('face_value', models.FloatField(null=True)),
                ('book_value', models.FloatField(null=True)),
                ('pe', models.FloatField(null=True)),
                ('roe', models.FloatField(null=True)),
                ('eps', models.FloatField(null=True)),
                ('ind_pe', models.FloatField(null=True)),
                ('roce', models.FloatField(null=True)),
                ('notes', models.CharField(max_length=1000, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
