# Generated by Django 5.1.6 on 2025-02-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_livetrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrade',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='trailing_stop_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='tsl_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
