# Generated by Django 5.1.6 on 2025-02-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_livetrade_profit_loss_livetrade_stop_loss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100)),
                ('stock_symbol', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_trades', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('profit_factor', models.FloatField()),
                ('max_drawdown', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
