# Generated by Django 5.1.6 on 2025-02-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_backtestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovingAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('sma_20', models.FloatField()),
                ('sma_50', models.FloatField()),
                ('open', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('signal', models.FloatField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
