# Generated by Django 5.1.6 on 2025-02-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_movingaverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
