# Generated by Django 5.1.6 on 2025-04-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stockprice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backtestresult',
            old_name='stock_symbol',
            new_name='stock_code',
        ),
        migrations.RenameField(
            model_name='livetrade',
            old_name='stock_symbol',
            new_name='stock_code',
        ),
        migrations.RenameField(
            model_name='movingaverage',
            old_name='stock_symbol',
            new_name='stock_code',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='symbol',
            new_name='stock_code',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='symbol',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='script',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='script',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='script',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='backtestresult',
            name='end_date',
            field=models.DateField(default='null', null=True),
        ),
        migrations.AlterField(
            model_name='movingaverage',
            name='date',
            field=models.DateTimeField(default='null', null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(default='null', null=True),
        ),
    ]
