# Generated by Django 5.1.6 on 2025-07-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_rename_stock_symbol_backtestresult_stock_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15)),
                ('script', models.CharField(max_length=15)),
                ('order_id', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=26)),
                ('stop_loss', models.FloatField(max_length=6)),
                ('qty', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('invested_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('day_pl', models.FloatField()),
                ('overall_pl', models.FloatField()),
                ('targets', models.JSONField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=266)),
                ('user_remark', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
