# Generated by Django 5.1.6 on 2025-11-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_position_size', models.DecimalField(decimal_places=2, default=100000, help_text='Maximum position size per trade', max_digits=12)),
                ('max_portfolio_exposure', models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum portfolio exposure percentage', max_digits=5)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=5000, help_text='Maximum daily loss limit', max_digits=12)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum drawdown percentage', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Risk Limits',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=10)),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], max_length=10)),
                ('strength', models.FloatField(default=0.5, help_text='Signal strength 0-1')),
                ('price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='stocks.strategy')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='stocks.livetrade')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stock_code', 'executed'], name='stocks_stra_stock_c_96b706_idx'), models.Index(fields=['strategy', 'timestamp'], name='stocks_stra_strateg_b04120_idx')],
            },
        ),
    ]
