# Generated by Django 5.1.6 on 2025-11-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_risklimits_strategy_strategysignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrade',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='entry_reason',
            field=models.TextField(blank=True, help_text='Reason for entering this trade'),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='exit_reason',
            field=models.TextField(blank=True, help_text='Reason for exiting this trade'),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='market_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Market conditions at trade time'),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional trade notes'),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='risk_reward_ratio',
            field=models.FloatField(blank=True, help_text='Risk to reward ratio', null=True),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_trades', to='stocks.strategysignal'),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='stocks.strategy'),
        ),
        migrations.AddField(
            model_name='livetrade',
            name='trade_duration',
            field=models.DurationField(blank=True, help_text='Duration of the trade', null=True),
        ),
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=10)),
                ('entry_date', models.DateTimeField(db_index=True)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pnl_percent', models.FloatField(default=0.0)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('risk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_reward_ratio', models.FloatField(blank=True, null=True)),
                ('max_favorable_excursion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_adverse_excursion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trade_duration', models.DurationField(blank=True, null=True)),
                ('entry_reason', models.TextField(blank=True)),
                ('exit_reason', models.TextField(blank=True)),
                ('market_conditions', models.JSONField(blank=True, default=dict)),
                ('trade_type', models.CharField(blank=True, choices=[('SCALP', 'Scalp'), ('DAY', 'Day Trade'), ('SWING', 'Swing Trade'), ('POSITION', 'Position Trade')], max_length=20, null=True)),
                ('win_loss', models.CharField(blank=True, choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('BREAKEVEN', 'Breakeven')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.strategy')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='stocks.livetrade')),
            ],
            options={
                'ordering': ['-entry_date'],
                'indexes': [models.Index(fields=['strategy', 'entry_date'], name='stocks_trad_strateg_cedc2e_idx'), models.Index(fields=['stock_code', 'entry_date'], name='stocks_trad_stock_c_b7447e_idx'), models.Index(fields=['win_loss', 'entry_date'], name='stocks_trad_win_los_30acba_idx')],
            },
        ),
    ]
