# Generated by Django 5.1 for Phase 2 trading desk

from django.db import migrations, models
import django.db.models.deletion


def copy_remaining_qty(apps, schema_editor):
    LiveTrade = apps.get_model("stocks", "LiveTrade")
    for trade in LiveTrade.objects.filter(remaining_quantity__isnull=True):
        trade.remaining_quantity = trade.quantity
        if not trade.entry_price and trade.price:
            trade.entry_price = trade.price
        trade.save(update_fields=["remaining_quantity", "entry_price"])


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0011_livetrade_entry_price_livetrade_entry_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stock_code", models.CharField(db_index=True, max_length=16)),
                ("ticker", models.CharField(blank=True, default="", max_length=50)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("source", models.CharField(choices=[("signal", "50MA status 8"), ("manual", "Manual")], default="signal", max_length=16)),
                ("status", models.CharField(choices=[("pending", "Pending review"), ("approved", "Approved"), ("rejected", "Rejected"), ("placed", "Order placed"), ("failed", "Place failed")], db_index=True, default="pending", max_length=16)),
                ("suggested_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("live_50ma", models.FloatField(blank=True, null=True)),
                ("cp50ma_percent", models.FloatField(blank=True, null=True)),
                ("qty", models.IntegerField(default=1)),
                ("order_type", models.CharField(choices=[("MARKET", "Market"), ("LIMIT", "Limit")], default="MARKET", max_length=10)),
                ("price_min", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("price_max", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("limit_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("stop_loss", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("take_profit", models.DecimalField(blank=True, decimal_places=2, help_text="Profit-booking limit (price).", max_digits=10, null=True)),
                ("take_profit_qty", models.IntegerField(blank=True, help_text="Qty to book when take-profit is hit. Blank = full qty.", null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("last_error", models.CharField(blank=True, default="", max_length=255)),
                ("reviewed_by", models.CharField(blank=True, default="", max_length=80)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("placed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tradereview",
            index=models.Index(fields=["stock_code", "status"], name="stocks_trad_stock_c_status_idx"),
        ),
        migrations.AddField(
            model_name="livetrade",
            name="remaining_quantity",
            field=models.IntegerField(blank=True, help_text="Open qty still held. Defaults to quantity on fill.", null=True),
        ),
        migrations.AddField(
            model_name="livetrade",
            name="profit_book_price",
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Human profit-booking limit (price).", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="livetrade",
            name="profit_book_qty",
            field=models.IntegerField(blank=True, help_text="Qty to sell when profit-book price is hit.", null=True),
        ),
        migrations.AddField(
            model_name="livetrade",
            name="price_min",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="livetrade",
            name="price_max",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="livetrade",
            name="source",
            field=models.CharField(choices=[("signal", "50MA signal"), ("manual", "Manual")], default="signal", max_length=16),
        ),
        migrations.AddField(
            model_name="livetrade",
            name="review",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fills", to="stocks.tradereview"),
        ),
        migrations.RunPython(copy_remaining_qty, migrations.RunPython.noop),
    ]
