# Generated by Django 5.1.6 on 2026-08-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_tradereview_and_livetrade_desk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tradereview',
            new_name='stocks_trad_stock_c_e3e7b9_idx',
            old_name='stocks_trad_stock_c_status_idx',
        ),
    ]
