# Generated by Django 5.1.6 on 2026-08-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_rename_stocks_trad_stock_c_status_idx_stocks_trad_stock_c_e3e7b9_idx'),
        ('stocks', '0013_tracked_source'),
    ]

    operations = [
    ]
